server:
  port: 8083

spring:
  application:
    name: house-service
  datasource:
    url: jdbc:postgresql://localhost:5432/housedb
    username: postgres
    password: 122432
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
