server:
  port: 8081

spring:
  application:
    name: spell-service
  datasource:
    url: jdbc:postgresql://localhost:5432/spelldb
    username: postgres
    password: 122432
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
